CREATE SCHEMA `hocba` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE testTable (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Cang VARCHAR(30) NOT NULL,
LoHoa VARCHAR(30) NOT NULL,
MaiCheo VARCHAR(50)
)